name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write # required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: hndn
          entrypoint: src/main.ts
